// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD37gX1mRSqCfJOPQP00JKG_MOqQlDVbP0',
    appId: '1:469142840204:web:250cd47fda50399d21eca9',
    messagingSenderId: '469142840204',
    projectId: 'project-wallet-ufpso',
    authDomain: 'project-wallet-ufpso.firebaseapp.com',
    storageBucket: 'project-wallet-ufpso.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6WCH9ENpuT0Z51Gvw3DIDeniwH5gW7iU',
    appId: '1:469142840204:android:ad9df591448a0bb021eca9',
    messagingSenderId: '469142840204',
    projectId: 'project-wallet-ufpso',
    storageBucket: 'project-wallet-ufpso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDg3IRD8ZJKqMIZ8tdm2MVjFKlMNlrSo',
    appId: '1:469142840204:ios:47c682982632a71021eca9',
    messagingSenderId: '469142840204',
    projectId: 'project-wallet-ufpso',
    storageBucket: 'project-wallet-ufpso.firebasestorage.app',
    iosBundleId: 'com.example.toDoUfpso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDg3IRD8ZJKqMIZ8tdm2MVjFKlMNlrSo',
    appId: '1:469142840204:ios:47c682982632a71021eca9',
    messagingSenderId: '469142840204',
    projectId: 'project-wallet-ufpso',
    storageBucket: 'project-wallet-ufpso.firebasestorage.app',
    iosBundleId: 'com.example.toDoUfpso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD37gX1mRSqCfJOPQP00JKG_MOqQlDVbP0',
    appId: '1:469142840204:web:a149b9318091c92521eca9',
    messagingSenderId: '469142840204',
    projectId: 'project-wallet-ufpso',
    authDomain: 'project-wallet-ufpso.firebaseapp.com',
    storageBucket: 'project-wallet-ufpso.firebasestorage.app',
  );
}
